[2024-11-15T20:19:01.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T20:19:02.010+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_DAG.extract manual__2024-11-15T20:18:58.896624+00:00 [queued]>
[2024-11-15T20:19:02.015+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_DAG.extract manual__2024-11-15T20:18:58.896624+00:00 [queued]>
[2024-11-15T20:19:02.022+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-11-15T20:19:02.035+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract> on 2024-11-15 20:18:58.896624+00:00
[2024-11-15T20:19:02.043+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T20:19:02.043+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG', 'extract', 'manual__2024-11-15T20:18:58.896624+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp9245vl6i']
[2024-11-15T20:19:02.044+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2024-11-15T20:19:02.045+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask extract
[2024-11-15T20:19:02.080+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_DAG.extract manual__2024-11-15T20:18:58.896624+00:00 [running]> on host 68c443489aab
[2024-11-15T20:19:02.158+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_DAG' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T20:18:58.896624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T20:18:58.896624+00:00'
[2024-11-15T20:19:02.160+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T20:19:02.160+0000] {DAG.py:26} INFO - Iniciando tarea de extracción.
[2024-11-15T20:19:02.194+0000] {DAG.py:31} ERROR - Error en la tarea de extracción: [Errno 2] No such file or directory: '/opt/***/dags/datasets/bussiness.parquet'
[2024-11-15T20:19:02.195+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T20:19:02.195+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/DAG.py", line 28, in extract
    df = pd.read_parquet('/opt/airflow/dags/datasets/bussiness.parquet')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/datasets/bussiness.parquet'
[2024-11-15T20:19:02.205+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_DAG, task_id=extract, execution_date=20241115T201858, start_date=20241115T201902, end_date=20241115T201902
[2024-11-15T20:19:02.219+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task extract ([Errno 2] No such file or directory: '/opt/airflow/dags/datasets/bussiness.parquet'; 58)
[2024-11-15T20:19:02.258+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T20:19:02.276+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T20:19:02.280+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
